title: Yourname's Homepage
page-top-title: 黄俊杰
top-section-bg-text: Nothing is True. Everything is permitted.
home-subtitle: 黄俊杰&ensp;|&ensp;华中科技大学
copyright-text: '&copy; Yourname 2024-2028. All Rights Reserved.'
